name: my_entrepreneurship
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc: ^8.1.3
  equatable: ^2.0.5
  firebase_auth: ^4.19.2
  firebase_core: ^2.27.0
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.18.1
  provider: ^6.1.2
  user_repository:
    path: packages/user_repository
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
