// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz67q6JdECwq5qQinOR6UDaXa2Bd51jP8',
    appId: '1:975739403574:android:cb6c4fe138991eff308797',
    messagingSenderId: '975739403574',
    projectId: 'my-entrepreneurship',
    databaseURL: 'https://my-entrepreneurship-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-entrepreneurship.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu7fb7-2h3QOUicziCuDfOpFf6rjLZvM4',
    appId: '1:975739403574:ios:b486d6e2668f7c29308797',
    messagingSenderId: '975739403574',
    projectId: 'my-entrepreneurship',
    databaseURL: 'https://my-entrepreneurship-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-entrepreneurship.appspot.com',
    iosBundleId: 'com.project.myEntrepreneurship',
  );

}